// Generated by LiveScript 1.3.1
var glslify;
glslify = require('glslify');
module.exports = {
  fragmentShader: glslify('precision highp float;\n#pragma glslify: gradient = require(\'../../raster/gradient/3d1.shader\')\n\nuniform vec2 uResolution;\nuniform float uTime;\nvoid main() {\n  vec2 uv = gl_FragCoord.xy / uResolution.xy;\n  vec3 pos;\n  float t = uTime * 0.1;\n  float c = 0.5;\n  float len;\n  /*\n  for(int i=0;i<100;i++) {\n    pos.x = fract(sin(float(i) * 52.643) * 735.5373) + sin(t + float(i)); \n    pos.y = fract(fract(sin(float(i) * 63.235) * 644.5346) - t);\n    pos.z = fract(sin(float(i) * 12.345) * 678.9012) * 0.01;\n    len = clamp(length(uv - pos.xy) - pos.z, 0., 1.);\n    c += 0.5 * pow(1. - len, 15.);\n  }\n  */\n  c = 1.;\n  gl_FragColor = vec4(\n    c * vec3(gradient(uv, vec3(1.,0.,0.), vec3(0.,1.,0.), vec3(0.,0.,1.), 3.)),\n    1.\n  );\n}')
};
