// Generated by LiveScript 1.3.1
var glslify, cloud;
glslify = require('glslify');
cloud = require("./sample/cloud");
window.addEventListener('load', function(){
  var shader, renderer;
  shader = {
    fragmentShader: glslify('precision highp float;\n#pragma glslify: aspect_ratio = require("../../src/aspect_ratio.shader")\n#pragma glslify: fbm = require("../../src/fbm.shader")\n#define PI2 6.2831852\n\nuniform float uTime;\nuniform vec2 uResolution;\nvoid main() {\n  float t = uTime * 0.25;\n  vec3 uv = aspect_ratio(uResolution, 1);\n  float color = 0.;\n  color = fbm(uv.x * uv.x + uv.y * uv.y * sin(t)) * smoothstep(1., 0., abs(uv.y - (sin(uv.x) * 0.2 + 0.5)) * 2.3);\n  gl_FragColor = vec4(vec3(color), 1.);\n\n}')
  };
  renderer = new ShaderRenderer([shader], {
    root: '#root'
  });
  return renderer.animate();
});