// Generated by LiveScript 1.3.1
var glslify;
glslify = require('glslify');
window.addEventListener('load', function(){
  var shader, renderer;
  shader = {
    uniforms: {
      color: {
        type: '3fv',
        value: [0, 0, 0]
      }
    },
    vertexShader: "precision highp float;\nuniform float uTime;\nattribute vec3 position;\nvoid main() {\n  gl_Position = vec4(position, 1.);\n}",
    fragmentShader: glslify('precision highp float;\n#pragma glslify: cloud = require(\'../../src/raster/cloud.shader\')\nuniform float uTime;\nuniform vec3 color;\nuniform vec2 uResolution;\nvoid main() {\n  float t = uTime;\n  vec2 uv = vec2(gl_FragCoord.x / uResolution.x, gl_FragCoord.y / uResolution.y);\n  float c = cloud(uv, t, vec2(1.0, 0.1), 4.);\n  gl_FragColor = vec4(c * color, 1.);\n}')
  };
  renderer = new shaderRenderer('#root', shader);
  return renderer.animate(function(t){
    return shader.uniforms.color.value = [1, 1, 1];
  });
});